### ISSUE TITLE
No module named hyperon

### ISSUE THREAD

**Issue by Eman22S** [trueagi-io/hyperon#7]
I tried running python on test_examples.py as follows:

`python test_examples.py` on my ubuntu 20.04. sadly I am getting this error:

`ModuleNotFoundError: No module named 'hyperon'`.

After some google search I learned that this might be a problem of not setting environment variables correctly. so I set
`$PYTHONPATH`  to `/home/user/hyperon/python/hyperon`. ​But I am still unable to get `test_examples.py` to run. 

I've installed and build everything according to the Read me and everything worked fine including `make tests`.
Any ideas ?

**Comment by vsbogd** [comment]
@Eman22S , thanks for reporting this. The `hyperon` library can be installed into the system using:
```
cd build
sudo make install
sudo ldconfig
```
After executing this commands you should be able to execute:
```
python -c "import hyperon"
```
without error.
Could you please check if it works for you and I will add it as an installation instruction to the `README.md` file.
